services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sales_point_frontend
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_API_URL: http://host.docker.internal:3000
      WATCHPACK_POLLING: "true"
      CHOKIDAR_USEPOLLING: "true"
    ports:
      - "3010:3010"
    volumes:
      - .:/app
      - /app/node_modules
    extra_hosts:
      - "host.docker.internal:host-gateway"
